name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Leiningen
      run: curl https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > lein
      run: chmod +x lein
      run: sudo mv lein /usr/local/bin/
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
